### ISSUE TITLE
gitlab pages imports not working on selfmanaged gitlab instance

### ISSUE THREAD

**Issue by dan-m8t** [jdoiro3/mkdocs-multirepo-plugin#142]
Hi,

I am playing around with mkdocs-multirepo-plugin and ran into an issue while I try to generate mkdocs and serve them with gitlab pages.

Versions used:

mkdocs-1.5.3
mkdocs-material-9.5.11
mkdocs-multirepo-plugin 0.7.0

Image used in CI/CD is python:3.8

This is my config:

```
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      # if set the docs directory will not be removed when importing docs.
      # When using this with a nav section in an imported repo you must keep the
      # docs directory in the path (e.g., docs/path/to/file.md).
      keep_docs_dir: true
      nav_repos:
        - name: okd-project
          import_url: https://github.com/okd-project/okd?branch=master
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [
            /README.md, /FAQ.md
            ]
        - name: okd-machine-os
          import_url: https://github.com/openshift/okd-machine-os?branch=master
          imports: [
            /README.md
            ]
        - name: harbor
          import_url: https://github.com/goharbor/harbor?branch=main
          imports: [
            /README.md
          ]

        - name: dm-test
          import_url: https://myselfhostedgitlab.local/justme/mydocs
          imports: [
            docs/ssh-agent.md
            ] 
```

This config works for both github entries, and I even tried a public gitlab.com readme.md. This also works. But I cannot get the plugin to work with my selfhosted gitlab. All I get is this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 277, in build
    config = config.plugins.on_config(config)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/plugins.py", line 527, in on_config
    return self.run_event('config', config)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 312, in on_config
    return self.handle_nav_repos_import(config, nav_repos)
  File "/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 256, in handle_nav_repos_import
    repo: DocsRepo = DocsRepo(
  File "/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 277, in __init__
    self.edit_uri = self._fix_edit_uri(edit_uri)
  File "/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 244, in _fix_edit_uri
    edit_uri_parts = edit_uri.strip("/").split("/")
AttributeError: 'NoneType' object has no attribute 'strip'
```

I was not sure if I need to build the URI like in the github examples, I played around with `mygitlab.local/group/project?branch=main` or `?ref_type=heads` but it seems not to  fix anything. Do you have a hint where to look into?

Thanks

**Comment by dan-m8t** [comment]
I was able to fix this. Hinted by this issue: https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/88 
I changed my URL from:

`https://myselfhostedgitlab.local/justme/mydocs`

to this:

`https://myselfhostedgitlab.local/justme/mydocs?branch=main&edit_uri=/blob/main`

and this works.
