### ISSUE TITLE
git tag's are not accepted or not fetched

### ISSUE THREAD

**Issue by andboss** [jdoiro3/mkdocs-multirepo-plugin#167]
Giving a tag as [documented](https://github.com/jdoiro3/mkdocs-multirepo-plugin#import-statement) instead of branch:

```
- name: oie-app-engineering
        import_url: https://my-server/app-template?branch=v1.4.0
        imports: [
          docs/*
          ]
```

we are facing the error:
```
Cloning into 'oie-app-engineering'...
warning: redirecting to https://my-server/app-template.git/
warning: Could not find remote branch v1.4.0 to clone.
fatal: Remote branch v1.4.0 not found in upstream origin
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line [168](https://code.siemens.com/oie-jupiter/documentation/user-doc/-/jobs/230247033#L168)8, in invoke
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 154 is closed
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 288, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 357, in build
    config.plugins.on_build_error(error=e)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 605, in on_build_error
    return self.run_event('build_error', error=error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 568, in run_event
    result = method(**kwargs)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_multirepo_plugin/plugin.py", line 361, in on_build_error
    shutil.rmtree(str(self.temp_dir))
  File "/usr/local/lib/python3.11/shutil.py", line 752, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.11/shutil.py", line 683, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/local/lib/python3.11/shutil.py", line 681, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: '.git'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fcc864089a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 566, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 590, in _close
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fcc864089a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 566, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 590, in _close
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fcc864089a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 566, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 590, in _close
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fcc864089a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 566, in close
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 590, in _close
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by andboss** [comment]
never mind, the tag was just wrong on my side, closing
