### ISSUE TITLE
No such file or directory: 'git' while using bitbucket

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [jdoiro3/mkdocs-multirepo-plugin#21]
Does this plugin support imports from bitbucket?

**Comment by jdoiro3** [comment]
@shanthisagar-dhanya-kumar-db, can you comment the Traceback so I can see the error messages?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
[59](XXXXURL/docs/default/component/adr#line-59)    asyncio_run(batch_import(repos))[60](XXXXURL/docs/default/component/adr#line-60)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 124, in asyncio_run[61](XXXXURL/docs/default/component/adr#line-61)    asyncio.run(futures)[62](XXXXURL/docs/default/component/adr#line-62)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/runners.py", line 44, in run[63](XXXXURL/docs/default/component/adr#line-63)    return loop.run_until_complete(main)[64](XXXXURL/docs/default/component/adr#line-64)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete[65](XXXXURL/docs/default/component/adr#line-65)    return future.result()[66](XXXXURL/docs/default/component/adr#line-66)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 264, in batch_import[67](XXXXURL/docs/default/component/adr#line-67)    repo = await import_async[68](XXXXURL/docs/default/component/adr#line-68)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/tasks.py", line 616, in _wait_for_one[69](XXXXURL/docs/default/component/adr#line-69)    return f.result()  # May raise f.exception().[70](XXXXURL/docs/default/component/adr#line-70)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 245, in import_docs[71](XXXXURL/docs/default/component/adr#line-71)    await self.sparse_clone([self.docs_dir, self.config])[72](XXXXURL/docs/default/component/adr#line-72)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 123, in sparse_clone[73](XXXXURL/docs/default/component/adr#line-73)    if git_supports_sparse_clone():[74](XXXXURL/docs/default/component/adr#line-74)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 89, in git_supports_sparse_clone[75](XXXXURL/docs/default/component/adr#line-75)    git_v = git_version()[76](XXXXURL/docs/default/component/adr#line-76)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 75, in git_version[77](XXXXURL/docs/default/component/adr#line-77)    output = subprocess.run(["git", "--version"], **extra_run_args)[78](XXXXURL/docs/default/component/adr#line-78)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 489, in run[79](XXXXURL/docs/default/component/adr#line-79)    with Popen(*popenargs, **kwargs) as process:[80](XXXXURL/docs/default/component/adr#line-80)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 854, in __init__[81](XXXXURL/docs/default/component/adr#line-81)    self._execute_child(args, executable, preexec_fn, close_fds,[82](XXXXURL/docs/default/component/adr#line-82)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child[83](XXXXURL/docs/default/component/adr#line-83)    raise child_exception_type(errno_num, err_msg, err_filename)[84](XXXXURL/docs/default/component/adr#line-84)FileNotFoundError: [Errno 2] No such file or directory: 'git'[85](XXXXURL/docs/default/component/adr#line-85):   0%|          | 0/2 [00:00<?, ?it/s][86](XXXXURL/docs/default/component/adr#line-86)Task exception was never retrieved[87](XXXXURL/docs/default/component/adr#line-87)future: <Task finished name='Task-3' coro=<DocsRepo.import_docs() done, defined at /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py:233> exception=FileNotFoundError(2, 'No such file or directory')>[88](XXXXURL/docs/default/component/adr#line-88)Traceback (most recent call last):[89](XXXXURL/docs/default/component/adr#line-89)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 245, in import_docs[90](XXXXURL/docs/default/component/adr#line-90)    await self.sparse_clone([self.docs_dir, self.config])[91](XXXXURL/docs/default/component/adr#line-91)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 123, in sparse_clone[92](XXXXURL/docs/default/component/adr#line-92)    if git_supports_sparse_clone():[93](XXXXURL/docs/default/component/adr#line-93)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 89, in git_supports_sparse_clone[94](XXXXURL/docs/default/component/adr#line-94)    git_v = git_version()[95](XXXXURL/docs/default/component/adr#line-95)  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 75, in git_version[96](XXXXURL/docs/default/component/adr#line-96)    output = subprocess.run(["git", "--version"], **extra_run_args)[97](XXXXURL/docs/default/component/adr#line-97)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 489, in run[98](XXXXURL/docs/default/component/adr#line-98)    with Popen(*popenargs, **kwargs) as process:[99](XXXXURL/docs/default/component/adr#line-99)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 854, in __init__[100](XXXXURL/docs/default/component/adr#line-100)    self._execute_child(args, executable, preexec_fn, close_fds,[101](XXXXURL/docs/default/component/adr#line-101)  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child[102](XXXXURL/docs/default/component/adr#line-102)    raise child_exception_type(errno_num, err_msg, err_filename)[103](XXXXURL/docs/default/component/adr#line-103)FileNotFoundError: [Errno 2] No such file or directory: 'git'

**Comment by shanthisagar-dhanya-kumar-db** [comment]
And my main mkdocs.yaml looks like this

site_name: 'ADRs'
site_description: 'Main documentation for Architecture Design Records'

repo_url: XXX
      
plugins:
  - techdocs-core
  - multirepo

nav:
  - Index: 'index.md'
  - CTO ADR: '!import XXXX/browse/CPDA-ADR/mkdocs.yaml'
  - GCP CDA ADR: '!import XXXX/browse/GCDA-ADR/mkdocs.yaml'

**Comment by shanthisagar-dhanya-kumar-db** [comment]
The error above "No such file or directory: 'git'", does this mean that there needs to have git installed on that server?

**Comment by jdoiro3** [comment]
@shanthisagar-dhanya-kumar-db, the plugin does require Git to be installed. 

If the OS is Linux/MacOS, it assumes it's installed on the machine, otherwise it try's to find the git directory. I need to update the documentation to point to the Git requirement and output better error messages when cases like this come up.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
I have now installed git and that specific issue got resolved. But I have another one

✅ Got GA ASR Docs:   0%|          | 0/1 [00:00<?, ?it/s]38✅ Got GA ASR Docs: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
✅ Got GA ASR Docs: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s]

3940Traceback (most recent call last):41  File "/opt/rh/rh-python38/root/usr/local/bin/mkdocs", line 8, in <module>42    sys.exit(cli())43  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__44    return self.main(*args, **kwargs)45  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main46    rv = self.invoke(ctx)47  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke48    return _process_result(sub_ctx.command.invoke(sub_ctx))49  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke50    return ctx.invoke(self.callback, **ctx.params)51  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke52    return __callback(*args, **kwargs)53  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 192, in build_command54    build.build(config.load_config(**kwargs), dirty=not clean)55  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 257, in build56    config = config['plugins'].run_event('config', config)57  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs/plugins.py", line 102, in run_event58    result = method(item, **kwargs)59  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 153, in on_config60    return self.handle_nav_based_import(config)61  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 108, in handle_nav_based_import62    repo_config = repo.load_config()63  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 251, in load_config64    config = super().load_config(self.config)65  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 149, in load_config66    raise ImportDocsException(f"{self.name} doesn't have {yml_file} at {str(config_file)}")67mkdocs_multirepo_plugin.util.ImportDocsException: GA ASR doesn't have mkdocs.yml at /tmp/backstage-l3mObl/temp_dir/GA ASR/mkdocs.yml

**Comment by shanthisagar-dhanya-kumar-db** [comment]
When I looked into the network share, it isn't creating the "temp_dir" under /tmp/backstage-l3mObl/

**Comment by jdoiro3** [comment]
@shanthisagar-dhanya-kumar-db, can you try running it on the machine without `backstage-techdocs`? The two plugins might be conflicting. If the same error occurs just running this plugin, it's obviously something wrong with `mkdocs-mutltirepo-plugin`. Hopefully we can figure out what's going on here.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Any thoughts on this?

**Comment by jdoiro3** [comment]
@shanthisagar-dhanya-kumar-db, can you try to run the plugin without backstage and confirm that it works? I think backstage techdocs and the plugin might be interfering with each other possibly.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
I tried setting cleanup=false but with no luck
We are hosting the docs under bitbucket. Would this create issue?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Does the below mean that the plugin was able to successfully clone the git project

![image](https://user-images.githubusercontent.com/86959288/172651854-e07543e7-c4d3-4924-a602-3b50c48e414c.png)

**Comment by shanthisagar-dhanya-kumar-db** [comment]
There were two issues basically
1) The bitbucket url which I had given was wrong. Instead of scm url, i gave browse url
2) I hadn't set the git credentials. ( it should have failed instead of saying Got XXXXX )

Now after setting the right credentials using the following
git config --global user.name "xxx"
git config --global user.email "xxx"
git config --global user.password "xxx"

it still fails with the same error. Basically, it wasn't able to get the files from remote to local.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
I can confirm that without backstage, it is working as expected.

With backstage techdocs-core plugin, it is failing. 

But, this is very strange that it is failing to git clone 

![image](https://user-images.githubusercontent.com/86959288/172730550-526d30cd-049d-4e81-8030-f3f0f4120554.png)

**Comment by shanthisagar-dhanya-kumar-db** [comment]
@jdoiro3 : Thanks for that. can we please do it sooner than later? Sorry for pushing this but in our organization there is this scenario that we have to use the multirepo plugin to demonstrate its goodness to the wider audience.
I can help with some of the things if you want to nail down on a date and time so that I can respond to this thread

**Comment by jdoiro3** [comment]
I'm on vacation until June 19th so it won't be until then. Feel free to fork the repo and try to figure out what's going on in this case. Also, buying me a beer (see link on README) increasing your chances I'll devote hours to the issue.
