### ISSUE TITLE
Error: failed to initialize sparse-checkout

### ISSUE THREAD

**Issue by dghelm** [jdoiro3/mkdocs-multirepo-plugin#23]
I'm having difficulty setting up the basic build, and would appreciate any insights into what is happening!

I'm running into the following error:

```
Traceback (most recent call last):
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs/commands/build.py", line 257, in build
    config = config['plugins'].run_event('config', config)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 156, in on_config
    return self.handle_repos_based_import(config, repos)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 130, in handle_repos_based_import
    asyncio_run(batch_import(docs_repo_objs))
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 124, in asyncio_run
    asyncio.run(futures)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 264, in batch_import
    repo = await import_async
  File "/usr/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 245, in import_docs
    await self.sparse_clone([self.docs_dir, self.config])
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 124, in sparse_clone
    stdout = await execute_bash_script("sparse_clone.sh", args, self.temp_dir)
  File "/home/dgh/dev/docTest/skynet-docs/mkdocs/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 118, in execute_bash_script
    raise GitException(f"\n{stderr}\n")

mkdocs_multirepo_plugin.util.GitException:
Cloning into 'Monorepo'...
fatal: cannot change to 'https://github.com/backstage/mkdocs-monorepo-plugin': No such file or directory
error: failed to initialize sparse-checkout
```

This is in Ubuntu, running in WSL2 on Windows, and an mkdocs.yml file with no `nav` section but the following under plugins:

```
  - multirepo:
      cleanup: true
      repos:
        - section: Monorepo
          import_url: 'https://github.com/backstage/mkdocs-monorepo-plugin'
          edit_uri: /blob/master/
```

**Comment by jdoiro3** [comment]
@dghelm, what version of Git are you using? I'll test this case with your version of Git and see if I can reproduce it. If you're able to update the version of Git, I'd try that too.

I suspect it's a bug on how I determine if the version of Git installed supports the newer [sparse-checkout](https://git-scm.com/docs/git-sparse-checkout) command or requires you do it another way. The relevant function is below.

https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/e75c8afb3836d51a969e9eff7f93f64e1e49aad9/mkdocs_multirepo_plugin/util.py#L88-L92

**Comment by dghelm** [comment]
> @dghelm, what version of Git are you using? I'll test this case with your version of Git and see if I can reproduce it. If you're able to update the version of Git, I'd try that too.
> 
> I suspect it's a bug on how I determine if the version of Git installed supports the newer [sparse-checkout](https://git-scm.com/docs/git-sparse-checkout) command or requires you do it another way. The relevant function is below.
> 
> https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/e75c8afb3836d51a969e9eff7f93f64e1e49aad9/mkdocs_multirepo_plugin/util.py#L88-L92

Oh, hadn't suspected that:
```
❯ git --version
git version 2.25.1
```

**Comment by grandeljay** [comment]
Hey,

Sorry for adding some noise here. I am having exactly this problem and am using exactly this version of git. I am going off-topic here but am quite desperate for any help you might be able to spare me.

I am using Plesk and it keeps telling me git is up to date. I am also using a Plesk git extension which is showing me a more up-to-date version but as soon as I type `git --version`  I get `2.25.1`. I have tried `apt-cache policy git` and the output also is indicating that git (2.25.1) is the most recent and up-to-date version.
