### ISSUE TITLE
Clarity in the documentation

### ISSUE THREAD

**Issue by kirannhegde** [jdoiro3/mkdocs-multirepo-plugin#3]
Hello,

To an end user of this plugin, it is not clear if the plugin even builds the documentation in the other repositories that it references.  It seems to me that the plugin does the following:
1)Reference **already built documentation in `other repositories**` and make use of them in this parent repository.

The plugin does not really build the documentation (i.e run mkdocs  build ) in each of the other repositories that the main repository references.  This should be made crystal clear so that end users know what the plugin is capable of.

The current wording in the documentation is ambiguous and is not clear.`

Thanks,
Kiran Hegde

**Comment by jdoiro3** [comment]
@kirannhegde, thanks for providing this feedback. The package lets you `import` (point might be a better word to use) to other repos, which contain markdown documentation (and possible code), and _builds the documentation in all these repos into one site_. Two reasons I can think of for why you might want this setup are:

- You have multiple repos and want documentation to live as close to the code as possible but findable on one site.
- You want to separate documentation from all the other files that goes into building the `mkdocs` site (e.g., theme overrides).

## Plugin Details

As far as what the plugin actually does, it uses your configuration in `mkdocs.yml` to perform Git [sparse checkout](https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/) to grab the markdown files (and a `mkdocs.yml` if you define the `nav` yourself) into a temporary directory. Once all the documentation is in the temporary directory, it tells `mkdocs` that documentation also lives here and we want it to be built in addition to the docs in the `docs` directory. The end result is that you have a _built_ site that contains docs from multiple repos.

@kirannhegde, does this clear things up for you or do you have any specific suggestions for how I can improve the documentation for this package?

**Comment by kirannhegde** [comment]
Hello @jdoiro3  Thanks for responding back. 
However, the documentation is still not clear.
![image](https://user-images.githubusercontent.com/4364390/153016782-f4879c01-4c54-4ce1-a271-405c96a33348.png)

The confusion arises from the above note. 
A typical repository will have a structure as follows:
![image](https://user-images.githubusercontent.com/4364390/153017122-20f370b9-95a1-4e22-a5cb-3fb768d77b78.png)

There is a **docs**  folder alongside other folders and a **mkdocs.yaml** file. However, your note in the documentation states that the repo's docs folder should have a mkdocs.yaml file. 
What **repo** are we referring to here?
Is it the parent repo which references other repo's in it's mkdocs.yaml file or is the child repo being referred to here?
**Need clarity on the same.**


So here is my requirement:
We have multiple repositories. Each of these repositories have their own **docs**  folder.  Each of these repositories have their own mkdocs.yaml file. In each of these mkdocs.yaml file, we make use of a plugin called **mkdocstrings**. This plugin, crawls through the source code and generates documentation for the same. However, the plugin during the process, also requires loading of the dependencies in the source code. 

Now our mkdocs **build** command is running inside of a container. I **could not** get this plugin to work. I see the following warning during my **mkdocs build**  command:

````
WARNING -  A relative path to '!import https://randomcompany@dev.azure.com/randomcompany/goy/_git/common' is included in the 'nav' configuration, which is not found in the documentation files 
maindocs    | WARNING -  Documentation file 'about_doc.md' contains a link to 'randomcompany.com' which is not found in the documentation files. 
maindocs    | WARNING -  Documentation file 'index-user.md' contains a link to '../imgs/buildings_good_inp.png' which is not found in the documentation files. 
maindocs    | WARNING -  Documentation file 'index-user.md' contains a link to '../imgs/buildings_good_inf.png' which is not found in the documentation files. 
maindocs    | WARNING -  Documentation file 'index-user.md' contains a link to '../imgs/buildings_good_vec.png' which is not found in the documentation files. 
maindocs    | INFO    -  Multirepo plugin is cleaning up temp_dir/ 
maindocs    | INFO    -  Documentation built in 0.42 seconds 
maindocs    | [I 220208 15:30:09 server:335] Serving on http://0.0.0.0:8000
maindocs    | INFO    -  Serving on http://0.0.0.0:8000
maindocs    | [I 220208 15:30:10 handlers:62] Start watching changes
maindocs    | INFO    -  Start watching changes
maindocs    | [I 220208 15:30:10 handlers:64] Start detecting changes
maindocs    | INFO    -  Start detecting changes
maindocs    | [I 220208 15:30:41 handlers:135] Browser Connected: http://0.0.0.0:8000/
maindocs    | INFO    -  Browser Connected: http://0.0.0.0:8000/
maindocs    | [W 220208 15:30:43 web:2239] 404 GET /!import%20https:/randomcompany@dev.azure.com/randomcompany/goy/_git/common (172.19.0.1) 3.95ms
maindocs    | WARNING -  404 GET /!import%20https:/randomcompany@dev.azure.com/randomcompany/goy/_git/common (172.19.0.1) 3.95ms
maindocs    | [I 220208 15:30:43 handlers:135] Browser Connected: http://0.0.0.0:8000/!import%20https:/randomcompany@dev.azure.com/randomcompany/goy/_git/common
maindocs    | INFO    -  Browser Connected: http://0.0.0.0:8000/!import%20https:/randomcompany@dev.azure.com/randomcompany/goy/_git/common
````
Any help would be very much appreciated.

**Comment by jdoiro3** [comment]
As far as the issues you're encountering with your container build, I'm not entirely sure. I'll need to look into it more closely/get help from someone with more experience. My team currently uses this plugin in an Azure Pipeline, deploying the built site to a server.

**Comment by jdoiro3** [comment]
I'm still relatively new to `mkdocstrings` but you could potentially change the configuration for `mkdocs-multirepo-plugin` to something like this.

*parent's (repo that imports other docs/code) mkdocs.yml*
```yml
plugins:
  - multirepo:
      repos:
        - section: MyModule
          import_url: {url}
          # import all the source code for mkdocstrings
          docs_dir: src/*
  - mkdocstrings
```

And in some markdown file within the parent repo have something like this, where `my_library` is located within `{temp_dir}/src`

```markdown
# Reference

::: my_library.my_module.my_class
```

The build steps for the project are:
- `mkdocs-multirepo-plugin` to import source code (temporarily) into a temp directory
- `mkdocstrings` then builds the documentation from the source code

**Comment by pawamoy** [comment]
Chiming in!

> In each of these mkdocs.yaml file, we make use of a plugin called mkdocstrings. This plugin, crawls through the source code and generates documentation for the same. However, the plugin during the process, also requires loading of the dependencies in the source code.

The new Python handler does not require to have the dependencies installed (unless you have some compiled modules in there). However, even with that, finding the sources to read them could be made impossible depending on the current working directory. This is a known issue in mkdocstrings and with have a ticket in the backlog: the idea is to behave like MkDocs itself and understand relative paths in the configuration as **relative to mkdocs.yml itself**, because you can specify the conf file on the CLI with the `-f` option without changing directory.

**Comment by pawamoy** [comment]
Try `mkdocstrings[python]>=0.18` :slightly_smiling_face: More info here: https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers

**Comment by AbhishekGS2021** [comment]
I'm trying to use mkdocs-multirepo-plugin basically to build site at local mkdoc setup by importing documents from your demo-repository

folder structure for my Repo1 directory (at my system) as below and repository to be imported is https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1

refered your comment: https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/3#issuecomment-1032804996

Parent repository
repo1/
   docs/
        index.md
        about.md
   mkdocs.yml
 
and
**mkdocs.yml** is

 plugins:
  - search
  - multirepo:
      cleanup: false
      keep_docs_dir: true

nav:
  - Home: index.md
  - About: about.md
  - DemoRepo: '!import https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1?branch=main'


after running mkdocs serve I'm getting below error please help on this @jdoiro3 

**Error 1:** BashException (I think the path is not getting constructed properly as "\" as missing

  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\util.py", line 139, in execute_bash_script
    raise BashException(f"\n{stderr_str}\n")
mkdocs_multirepo_plugin.util.BashException:
/bin/bash: C:UsersSheelvantAppDataLocalProgramsPythonPython312Libsite-packagesmkdocs_multirepo_pluginscriptssparse_clone.sh: No such file or directory

**Error 2:**   File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 637, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\docgen\\repo1\\venv\\temp_dir'

these where the main errors ,
i have listed down the all errors at below

S C:\docgen\repo1\venv> mkdocs serve
INFO    -  Building documentation...
INFO    -  Multirepo plugin importing docs...
🔳 demorepo
Traceback (most recent call last):
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\build.py", line 265, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 587, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 566, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 310, in on_config
    config = self.handle_nav_import(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 180, in handle_nav_import
    asyncio_run(batch_import(repos, keep_docs_dir=keep_docs_dir))
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\util.py", line 145, in asyncio_run
    asyncio.run(futures)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 427, in batch_import
    await batch_execute(
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 419, in batch_execute
    repo = await future
           ^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 391, in import_docs
    await self.sparse_clone([self.docs_dir, self.config] + self.extra_imports)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 193, in sparse_clone
    await execute_bash_script("sparse_clone.sh", args, self.temp_dir)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\util.py", line 139, in execute_bash_script
    raise BashException(f"\n{stderr_str}\n")
mkdocs_multirepo_plugin.util.BashException:
/bin/bash: C:UsersSheelvantAppDataLocalProgramsPythonPython312Libsite-packagesmkdocs_multirepo_pluginscriptssparse_clone.sh: No such file or directory



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\__main__.py", line 272, in serve_command        
    serve.serve(**kwargs)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\serve.py", line 85, in serve
    builder(config)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\build.py", line 357, in build
    config.plugins.on_build_error(error=e)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 605, in on_build_error        
    return self.run_event('build_error', error=error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 568, in run_event
    result = method(**kwargs)
             ^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 361, in on_build_error
    shutil.rmtree(str(self.temp_dir))
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 781, in rmtree
    return _rmtree_unsafe(path, onexc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 639, in _rmtree_unsafe
    onexc(os.rmdir, path, err)
  File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 637, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\docgen\\repo1\\venv\\temp_dir'

**Comment by kvdogan** [comment]
> I'm trying to use mkdocs-multirepo-plugin basically to build site at local mkdoc setup by importing documents from your demo-repository
> 
> folder structure for my Repo1 directory (at my system) as below and repository to be imported is https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1
> 
> refered your comment: [#3 (comment)](https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/3#issuecomment-1032804996)
> 
> Parent repository repo1/ docs/ index.md about.md mkdocs.yml
> 
> and **mkdocs.yml** is
> 
> plugins:
> 
> * search
> * multirepo:
>   cleanup: false
>   keep_docs_dir: true
> 
> nav:
> 
> * Home: index.md
> * About: about.md
> * DemoRepo: '!import https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1?branch=main'
> 
> after running mkdocs serve I'm getting below error please help on this [@jdoiro3](https://github.com/jdoiro3)
> 
> **Error 1:** BashException (I think the path is not getting constructed properly as "" as missing
> 
> File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\util.py", line 139, in execute_bash_script raise BashException(f"\n{stderr_str}\n") mkdocs_multirepo_plugin.util.BashException: /bin/bash: C:UsersSheelvantAppDataLocalProgramsPythonPython312Libsite-packagesmkdocs_multirepo_pluginscriptssparse_clone.sh: No such file or directory
> 
> **Error 2:** File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 637, in _rmtree_unsafe os.rmdir(path) PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\docgen\repo1\venv\temp_dir'
> 
> these where the main errors , i have listed down the all errors at below
> 
> S C:\docgen\repo1\venv> mkdocs serve INFO - Building documentation... INFO - Multirepo plugin importing docs... 🔳 demorepo Traceback (most recent call last): File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\build.py", line 265, in build config = config.plugins.on_config(config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 587, in on_config return self.run_event('config', config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 566, in run_event result = method(item, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 310, in on_config config = self.handle_nav_import(config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 180, in handle_nav_import asyncio_run(batch_import(repos, keep_docs_dir=keep_docs_dir)) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\util.py", line 145, in asyncio_run asyncio.run(futures) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 427, in batch_import await batch_execute( File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 419, in batch_execute repo = await future ^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 631, in _wait_for_one return f.result() # May raise f.exception(). ^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 391, in import_docs await self.sparse_clone([self.docs_dir, self.config] + self.extra_imports) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 193, in sparse_clone await execute_bash_script("sparse_clone.sh", args, self.temp_dir) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\util.py", line 139, in execute_bash_script raise BashException(f"\n{stderr_str}\n") mkdocs_multirepo_plugin.util.BashException: /bin/bash: C:UsersSheelvantAppDataLocalProgramsPythonPython312Libsite-packagesmkdocs_multirepo_pluginscriptssparse_clone.sh: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Scripts\mkdocs.exe__main__.py", line 7, in File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in **call** return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs__main__.py", line 272, in serve_command serve.serve(**kwargs) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\serve.py", line 85, in serve builder(config) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\serve.py", line 67, in builder build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\commands\build.py", line 357, in build config.plugins.on_build_error(error=e) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 605, in on_build_error return self.run_event('build_error', error=error) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs\plugins.py", line 568, in run_event result = method(**kwargs) ^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 361, in on_build_error shutil.rmtree(str(self.temp_dir)) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 781, in rmtree return _rmtree_unsafe(path, onexc) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 639, in _rmtree_unsafe onexc(os.rmdir, path, err) File "C:\Users\Sheelvant\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 637, in _rmtree_unsafe os.rmdir(path) PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\docgen\repo1\venv\temp_dir'

Hi, I am wondering if you have been able to resolve that error?
