### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by tsladecek** [jdoiro3/mkdocs-multirepo-plugin#47]
I am having problems when including multiple repositories in the nav section.

When only one `!import ...` statement is included everything works fine. I get asked for a `username` and then `Password` and the authentication proceeds as expected (see the first image). However, when I include a second repository (in the same GitLab group) it gets messed up.

It asks me multiple times for a username and password. And whenever I try to fill the password out, it proceeds by asking me to fill it again with the username now being the password I just typed in (see the second image).

The only way I found this to be working, is to uncomment all `!import` statements at startup except for one, input my username and password and then uncomment all the commented lines. But this is not acceptable

p.s. We are running our own GitLab instance on a remote server

---
![multirepo_working](https://user-images.githubusercontent.com/32832542/183365300-98606d08-333f-44b1-ae8c-8569c32098b9.jpg)
![multirepo_not_working](https://user-images.githubusercontent.com/32832542/183365296-ecfb2db7-9b84-4927-870c-33ef21c8b195.jpg)

---
This is the Traceback I get when running mkdocs serve in vscode:

```
INFO     -  Building documentation...
INFO     -  Multirepo plugin importing docs...
                                    :   0%|                                                                                                                                                                                              | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs/commands/build.py", line 257, in build
    config = config['plugins'].run_event('config', config)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 167, in on_config
    return self.handle_nav_based_import(config)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs_multirepo_plugin/plugin.py", line 110, in handle_nav_based_import
    asyncio_run(batch_import(repos))
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 135, in asyncio_run
    asyncio.run(futures)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 326, in batch_import
    repo = await import_async
  File "/usr/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 307, in import_docs
    await self.sparse_clone([self.docs_dir, self.config] + self.extra_imports)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs_multirepo_plugin/structure.py", line 176, in sparse_clone
    stdout = await execute_bash_script("sparse_clone.sh", args, self.temp_dir)
  File "/home/tomas/.local/share/virtualenvs/documentation-cCftB_zg/lib/python3.8/site-packages/mkdocs_multirepo_plugin/util.py", line 129, in execute_bash_script
    raise BashException(f"\n{stderr}\n")
mkdocs_multirepo_plugin.util.BashException: 
Cloning into 'microservices/backend-api'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for ...
```

**Comment by tsladecek** [comment]
It works with ssh links, which is acceptable for me. However it might be an issue for someone in the future.
