### ISSUE TITLE
Temp dir issue

### ISSUE THREAD

**Issue by SteveRosam** [jdoiro3/mkdocs-multirepo-plugin#70]
I'm getting this when trying to build.

The process cannot access the file because it is being used by another process

I have deleted the temp_dir and still get the same. Has anyone found a work around and is there a build flag or argument to change the temp directory?

**Comment by jdoiro3** [comment]
@SteveRosam, can you please provide the traceback?

**Comment by bruindev** [comment]
I have the same issue, only got this issue from window machine 

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Git\\Docs\\temp_dir'

**Comment by theKomix** [comment]
I have same problem:

INFO     -  Multirepo plugin importing docs...
🔳 wiki-js
DEBUG    -  Running 1 `build_error` events
Traceback (most recent call last):
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs\commands\build.py", line 270, in build
    config = config.plugins.run_event('config', config)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs\plugins.py", line 520, in run_event
    result = method(item, **kwargs)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 312, in on_config
    return self.handle_nav_repos_import(config, nav_repos)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 270, in handle_nav_repos_import
    asyncio_run(batch_execute(repos=docs_repo_objs, method=Repo.sparse_clone))
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs_multirepo_plugin\util.py", line 114, in asyncio_run
    asyncio.run(futures)
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 407, in batch_execute
    repo = await future
  File "C:\Python310\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 193, in sparse_clone
    await execute_bash_script("sparse_clone.sh", args, self.temp_dir)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs_multirepo_plugin\util.py", line 108, in execute_bash_script
    raise BashException(f"\n{stderr}\n")
mkdocs_multirepo_plugin.util.BashException:

**Comment by theKomix** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Source\gitlab\wfcore-docs\venv\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs\__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs\commands\build.py", line 343, in build
    config.plugins.run_event('build_error', error=e)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs\plugins.py", line 522, in run_event
    result = method(**kwargs)
  File "C:\Source\gitlab\wfcore-docs\venv\lib\site-packages\mkdocs_multirepo_plugin\plugin.py", line 356, in on_build_error
    shutil.rmtree(str(self.temp_dir))
  File "C:\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python310\lib\shutil.py", line 623, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python310\lib\shutil.py", line 621, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Source\\gitlab\\wfcore-docs\\temp_dir'

**Comment by theKomix** [comment]
And another problem with temp_dir in gitlab pipeline:
FileNotFoundError: [Errno 2] No such file or directory: '/builds/wfcore-team/wfcore-docs/temp_dir'

✅ wiki-js (2.246 secs)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 337, in build
    raise Abort(f'\nAborted with {msg} in strict mode!')
mkdocs.exceptions.Abort: 
Aborted with 2 warnings in strict mode!
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 343, in build
    config.plugins.run_event('build_error', error=e)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/plugins.py", line 522, in run_event
    result = method(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs_multirepo_plugin/plugin.py", line 356, in on_build_error
    shutil.rmtree(str(self.temp_dir))
  File "/usr/local/lib/python3.10/shutil.py", line 715, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/lib/python3.10/shutil.py", line 713, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/builds/wfcore-team/wfcore-docs/temp_dir'

**Comment by imanousar** [comment]
I get the same error when I run **mkdocs serve**.

***mkdocs.yml***
```
site_name: Mkdocs
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      nav_repos:
        - name: backstage
          import_url: https://github.com/backstage/backstage
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [
              docs/publishing.md,
              docs/integrations/index.md,
              /README.md,
              # asset files needed
              docs/assets/*,
            ]
        - name: fast-api
          import_url: https://github.com/tiangolo/fastapi
          imports: [docs/en/docs/index.md]

nav:
  - Backstage:
      - Home: backstage/README.md
      - Integration: backstage/docs/integrations/index.md
      - Publishing: backstage/docs/publishing.md
  - FastAPI: fast-api/docs/en/docs/index.md
  # you can still use the !import statement
  - MkdocStrings: "!import https://github.com/mkdocstrings/mkdocstrings"

```

**Comment by amsvenkat-ai** [comment]
Any solution for the above?
