### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by tepene** [jdoiro3/mkdocs-multirepo-plugin#8]
while trying out the plugin, I enabled it after the installation with:

```yaml
plugins:
  - multirepo
```
After that I wanted to start the builtin development server with `mkdocs serve`. But while doing so I get the following error:

**Error Message**
```
INFO     -  Building documentation...
INFO     -  Multirepo plugin importing docs...
Traceback (most recent call last):
  File "/home/vscode/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vscode/.local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 177, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = builder()
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 257, in build
    config = config['plugins'].run_event('config', config)
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs_multirepo_plugin/plugin.py", line 165, in on_config
    return self.handle_nav_based_import(config)
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs_multirepo_plugin/plugin.py", line 117, in handle_nav_based_import
    asyncio_run(batch_import(docs_repo_objs))
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs_multirepo_plugin/util.py", line 117, in asyncio_run
    asyncio.run(futures)
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/vscode/.local/lib/python3.10/site-packages/mkdocs_multirepo_plugin/structure.py", line 185, in batch_import
    longest_desc = max([len(f"✅ Got {repo.name} Docs") for repo in repos])
ValueError: max() arg is an empty sequence
The terminal process "/usr/bin/zsh '-c', 'mkdocs serve'" terminated with exit code: 1.
```
Am I missing something?

**Comment by jdoiro3** [comment]
@tepene, did you provide any repos to the `nav` or `repos` section in your `mkdocs.yml` file? The plugin expects to have at least one repo specified in one of those sections. I'll either add a better error message or just handle it by doing nothing.

**Comment by tepene** [comment]
I get the same error with and without configured repos:

```yaml
plugins:
  - multirepo:
      cleanup: true
      repos:
        - section: Backstage
          import_url: "https://github.com/backstage/backstage"
          edit_uri: /blob/master/
```
I first tried it with my GitLab repos and after a failed attempt I tried it with the example from your documentation.

Still the same error.

**Comment by jdoiro3** [comment]
@tepene, can you tell me what OS and version of Python you're using? Trying to figure out what's going on here.

**Comment by jdoiro3** [comment]
@tepene, sorry for never circling back on this issue. I know you might have moved away from using this plugin but wondering if this is still an issue/bug when using newer versions of the plugin. Do you still get this error with version `v0.4.8`?

**Comment by tepene** [comment]
I haven't tested it yet with `v0.4.8`. I'll update my post once I've done that. Will take some time though.

**Comment by tepene** [comment]
@jdoiro3 Sorry for the late. I now found some time to do some more testing.

The following setup did now work:

```bash
$ pip list | grep mkd
mkdocs                     1.4.1
mkdocs-material            8.5.7
mkdocs-material-extensions 1.1
mkdocs-multirepo-plugin    0.4.12
mkdocs-with-pdf            0.9.3
```

```yaml
plugins:
  - multirepo:
  - 
nav:
  - Test-Multirepo: "!import https://github.com/backstage/backstage?edit_uri=/blob/master/"
```

which gives this navigation tree:
![image](https://user-images.githubusercontent.com/54766327/197970379-ecdc1b28-6504-45bc-b176-2512ade48f34.png)

Thanks for your great work!
