### ISSUE TITLE
Issue with nav_repo and import_url

### ISSUE THREAD

**Issue by kbober-kenzan** [jdoiro3/mkdocs-multirepo-plugin#88]
We are using GitLab and this works fine when using !import in the 'nav' section. 

What we want to do is only import certain markdown files from a GitLab repo to include in our generated MKDocs site. 
Our understanding is this is possible with the 'nav_repos' configuration.

We are experiencing the following error when attempting to use 'mkdocs-multirepo-plugin' and the plugin configuration using 'nav_repos'.  Also, should we be able to use the HTTPS and SSH protocols interchangeably for the nav_repos.import_url value?

Here is my markdown.yml file:
`site_name: Istio Sample

nav:
  - Istio: istio/README.md

plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      nav_repos:
        - name: istio
#          import_url: git@gitlab.ourdomain.net:istio?branch=some_branch
          import_url: https://gitlab.ourdomain.net:istio?branch=some_branch
          imports: [/README.md]`

Here is the error I see when attempting to serve the MKDocs site:

`
WARNING  -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However,
            the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO     -  Building documentation...
INFO     -  Multirepo plugin importing docs...
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 270, in build
    config = config.plugins.run_event('config', config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_multirepo_plugin/plugin.py", line 312, in on_config
    return self.handle_nav_repos_import(config, nav_repos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_multirepo_plugin/plugin.py", line 256, in handle_nav_repos_import
    repo: DocsRepo = DocsRepo(
                     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_multirepo_plugin/structure.py", line 274, in __init__
    self.edit_uri = self._fix_edit_uri(edit_uri)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_multirepo_plugin/structure.py", line 241, in _fix_edit_uri
    edit_uri_parts = edit_uri.strip("/").split("/")
                     ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
`

This works fine with the !import configuration in the 'nav' section:

`site_name: Istio Sample

nav:
  - Istio: '!import git@gitlab.ourdomain.net:istio?branch=some_branch'

plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: true`

**Comment by jdoiro3** [comment]
Can you try to set the edit uri for the repo or the globally in your yaml config? I'll need to fix this in the next release but thinking that might fix it.

**Comment by jdoiro3** [comment]
@kbober-kenzan, 

> Can you try to set the edit uri for the repo or the globally in your yaml config? I'll need to fix this in the next release but thinking that might fix it.

@kbober-kenzan, did this fix it? I'm planning on working on this project some more in the next few weeks.

**Comment by dchesterman** [comment]
Worked for us.
